/**
 * This class is generated by jOOQ
 */
package csmart.db.gen.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders extends org.jooq.impl.TableImpl<csmart.db.gen.tables.records.OrdersRecord> {

	private static final long serialVersionUID = -1309257610;

	/**
	 * The singleton instance of <code>public.orders</code>
	 */
	public static final csmart.db.gen.tables.Orders ORDERS = new csmart.db.gen.tables.Orders();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<csmart.db.gen.tables.records.OrdersRecord> getRecordType() {
		return csmart.db.gen.tables.records.OrdersRecord.class;
	}

	/**
	 * The column <code>public.orders.order_id</code>.
	 */
	public final org.jooq.TableField<csmart.db.gen.tables.records.OrdersRecord, java.lang.String> ORDER_ID = createField("order_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>public.orders.emailid</code>.
	 */
	public final org.jooq.TableField<csmart.db.gen.tables.records.OrdersRecord, java.lang.String> EMAILID = createField("emailid", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * Create a <code>public.orders</code> table reference
	 */
	public Orders() {
		this("orders", null);
	}

	/**
	 * Create an aliased <code>public.orders</code> table reference
	 */
	public Orders(java.lang.String alias) {
		this(alias, csmart.db.gen.tables.Orders.ORDERS);
	}

	private Orders(java.lang.String alias, org.jooq.Table<csmart.db.gen.tables.records.OrdersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Orders(java.lang.String alias, org.jooq.Table<csmart.db.gen.tables.records.OrdersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, csmart.db.gen.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<csmart.db.gen.tables.records.OrdersRecord> getPrimaryKey() {
		return csmart.db.gen.Keys.ORDERS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<csmart.db.gen.tables.records.OrdersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<csmart.db.gen.tables.records.OrdersRecord>>asList(csmart.db.gen.Keys.ORDERS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public csmart.db.gen.tables.Orders as(java.lang.String alias) {
		return new csmart.db.gen.tables.Orders(alias, this);
	}

	/**
	 * Rename this table
	 */
	public csmart.db.gen.tables.Orders rename(java.lang.String name) {
		return new csmart.db.gen.tables.Orders(name, null);
	}
}
